version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - AUTOENCODER_MODEL_PATH=/app/models/autoencoder_latest/autoencoder_model.h5
      - BIGRU_MODEL_PATH=/app/models/bigru_attention_latest/bigru_attention_model.h5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
